name: app_porteiro
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  validatorless: ^1.2.3
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  mask_text_input_formatter: ^2.4.0
  onesignal_flutter: ^3.4.2
  shimmer: ^2.0.0
  intl: ^0.18.1
  flutter_speed_dial: ^7.0.0
  crypto: ^3.0.3
  local_auth: ^2.1.6
  flutter_launcher_icons: ^0.13.1
  dropdown_search: ^5.0.6
  flutter_html: ^3.0.0-alpha.3
  signature: ^5.4.0
  dio: ^5.3.1
  image_picker: ^1.0.1
  url_launcher: ^6.1.11
  fluttertoast: ^8.2.2

flutter_icons:  
  
  image_path: "assets/logo-vermelho.png"
  ios: true
  remove_alpha_ios: true
  android: "launch_icon"
  adaptive_icon_foreground: "assets/logo-vermelho.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/