name: app_porteiro
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  validatorless: ^1.2.3
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  mask_text_input_formatter: ^2.4.0
  onesignal_flutter: ^3.4.2
  shimmer: ^2.0.0
  intl: 
  flutter_speed_dial: ^7.0.0
  crypto: ^3.0.3
  local_auth: ^2.1.6
  flutter_launcher_icons: ^0.13.1
  dropdown_search: ^5.0.6
  signature: ^5.4.0
  dio: ^5.3.1
  image_picker: ^1.0.1
  url_launcher: ^6.1.11
  fluttertoast: ^8.2.2
  badges: ^3.1.1
  permission_handler: ^10.4.3
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.0
  flutter_html: ^3.0.0-alpha.3
  flutter_local_notifications: ^15.1.1
  cached_network_image: ^3.2.3
  date_time_picker: ^2.1.0

flutter_icons:  
  
  image_path: "assets/launch_icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launch_icon"
  adaptive_icon_foreground: "assets/launch_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/